// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQz8TYZS2Nh_465Z2yUwT3-OZSdxYTwvo',
    appId: '1:504726617718:web:ebb4b3b3dfc47360692957',
    messagingSenderId: '504726617718',
    projectId: 'notification-app-7edce',
    authDomain: 'notification-app-7edce.firebaseapp.com',
    storageBucket: 'notification-app-7edce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZkZoCaFiJ6Q9FIQF7b956eXxqrohotU8',
    appId: '1:504726617718:android:d088cbd2857a3d90692957',
    messagingSenderId: '504726617718',
    projectId: 'notification-app-7edce',
    storageBucket: 'notification-app-7edce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_shy9WKMUiZIPW0YzT28lqkrmtuwHUes',
    appId: '1:504726617718:ios:0496370bd89bb8d2692957',
    messagingSenderId: '504726617718',
    projectId: 'notification-app-7edce',
    storageBucket: 'notification-app-7edce.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_shy9WKMUiZIPW0YzT28lqkrmtuwHUes',
    appId: '1:504726617718:ios:0496370bd89bb8d2692957',
    messagingSenderId: '504726617718',
    projectId: 'notification-app-7edce',
    storageBucket: 'notification-app-7edce.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQz8TYZS2Nh_465Z2yUwT3-OZSdxYTwvo',
    appId: '1:504726617718:web:40d9b0dbad66c816692957',
    messagingSenderId: '504726617718',
    projectId: 'notification-app-7edce',
    authDomain: 'notification-app-7edce.firebaseapp.com',
    storageBucket: 'notification-app-7edce.firebasestorage.app',
  );
}
